compressionLevel: mixed

nodeLinker: "node-modules"

enableGlobalCache: true

enableHardenedMode: true

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.1.1.cjs
