compressionLevel: mixed

enableGlobalCache: true

enableHardenedMode: true

nodeLinker: node-modules

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.9.2.cjs
