/* eslint-disable */

declare module "@babel/code-frame" { declare module.exports: any; }
declare module "@babel/core" { declare module.exports: any; }
declare module "@babel/generator" { declare module.exports: any; }
declare module "@babel/helper-module-imports" { declare module.exports: any; }
declare module "@babel/helpers" { declare module.exports: any; }
declare module "@babel/preset-es2015" { declare module.exports: any; }
declare module "@babel/template" { declare module.exports: any; }
declare module "@babel/types" { declare module.exports: any; }
declare module "@quase/cacheable-fs" { declare module.exports: any; }
declare module "@quase/cli" { declare module.exports: any; }
declare module "@quase/config" { declare module.exports: any; }
declare module "@quase/error" { declare module.exports: any; }
declare module "@quase/find-files" { declare module.exports: any; }
declare module "@quase/get-plugins" { declare module.exports: any; }
declare module "@quase/memory-fs" { declare module.exports: any; }
declare module "@quase/path-url" { declare module.exports: any; }
declare module "@quase/source-map" { declare module.exports: any; }
declare module "ansi-styles" { declare module.exports: any; }
declare module "babel-preset-minify" { declare module.exports: any; }
declare module "babylon" { declare module.exports: any; }
declare module "boxen" { declare module.exports: any; }
declare module "chalk" { declare module.exports: any; }
declare module "circular-json" { declare module.exports: any; }
declare module "concordance" { declare module.exports: any; }
declare module "encode-registry" { declare module.exports: any; }
declare module "error-stack-parser" { declare module.exports: any; }
declare module "file-url" { declare module.exports: any; }
declare module "filenamify" { declare module.exports: any; }
declare module "fs-extra" { declare module.exports: any; }
declare module "glob-parent" { declare module.exports: any; }
declare module "has-yarn" { declare module.exports: any; }
declare module "ignore-by-default" { declare module.exports: any; }
declare module "import-fresh" { declare module.exports: any; }
declare module "is-ci" { declare module.exports: boolean; }
declare module "is-installed-globally" { declare module.exports: any; }
declare module "is-url-superb" { declare module.exports: any; }
declare module "jsdom" { declare module.exports: any; }
declare module "json5" { declare module.exports: any; }
declare module "klaw" { declare module.exports: any; }
declare module "leven" { declare module.exports: any; }
declare module "load-json-file" { declare module.exports: any; }
declare module "log-symbols" { declare module.exports: any; }
declare module "magic-string" { declare module.exports: any; }
declare module "matcher" { declare module.exports: any; }
declare module "meow" { declare module.exports: any; }
declare module "micromatch" { declare module.exports: any; }
declare module "node-fetch" { declare module.exports: any; }
declare module "normalize-package-data" { declare module.exports: any; }
declare module "normalize-path" { declare module.exports: any; }
declare module "npm-lifecycle" { declare module.exports: any; }
declare module "npm-package-arg" { declare module.exports: any; }
declare module "npmlog" { declare module.exports: any; }
declare module "ora" { declare module.exports: any; }
declare module "pacote" { declare module.exports: any; }
declare module "parse-npm-tarball-url" { declare module.exports: any; }
declare module "parse5" { declare module.exports: any; }
declare module "parse5/lib/tree-adapters/default" { declare module.exports: any; }
declare module "pkg-conf" { declare module.exports: any; }
declare module "pretty-bytes" { declare module.exports: any; }
declare module "random-js" { declare module.exports: any; }
declare module "rc" { declare module.exports: any; }
declare module "read-pkg" { declare module.exports: any; }
declare module "read-pkg-up" { declare module.exports: any; }
declare module "require-relative" { declare module.exports: any; }
declare module "resolve" { declare module.exports: any; }
declare module "resolve-from" { declare module.exports: any; }
declare module "slash" { declare module.exports: any; }
declare module "source-map" { declare module.exports: any; }
declare module "strip-url-auth" { declare module.exports: any; }
declare module "sw-precache" { declare module.exports: any; }
declare module "symlink-dir" { declare module.exports: any; }
declare module "update-notifier" { declare module.exports: any; }
declare module "watchpack" { declare module.exports: any; }
declare module "write-file-atomic" { declare module.exports: any; }
declare module "write-json-file" { declare module.exports: any; }
declare module "write-pkg" { declare module.exports: any; }
declare module "zen-observable" { declare module.exports: any; }
