/* eslint-disable */

declare module "@quase/source-map" { declare var exports: any; }
declare module "@quase/memory-fs" { declare var exports: any; }
declare module "@quase/error" { declare var exports: any; }
declare module "@quase/path-url" { declare var exports: any; }
declare module "@babel/core" { declare var exports: any; }
declare module "@babel/preset-es2015" { declare var exports: any; }
declare module "babel-preset-minify" { declare var exports: any; }
declare module "is-ci" { declare var exports: boolean; }
declare module "matcher" { declare var exports: any; }
declare module "fs-extra" { declare var exports: any; }
declare module "pacote" { declare var exports: any; }
declare module "read-pkg" { declare var exports: any; }
declare module "write-pkg" { declare var exports: any; }
declare module "load-json-file" { declare var exports: any; }
declare module "write-json-file" { declare var exports: any; }
declare module "filenamify" { declare var exports: any; }
declare module "strip-url-auth" { declare var exports: any; }
declare module "normalize-package-data" { declare var exports: any; }
declare module "npm-package-arg" { declare var exports: any; }
declare module "rc" { declare var exports: any; }
declare module "npmlog" { declare var exports: any; }
declare module "encode-registry" { declare var exports: any; }
declare module "normalize-path" { declare var exports: any; }
declare module "parse-npm-tarball-url" { declare var exports: any; }
declare module "klaw" { declare var exports: any; }
declare module "symlink-dir" { declare var exports: any; }
declare module "watchpack" { declare var exports: any; }
declare module "file-url" { declare var exports: any; }
declare module "slash" { declare var exports: any; }
declare module "is-url-superb" { declare var exports: any; }
declare module "pretty-bytes" { declare var exports: any; }
declare module "concordance" { declare var exports: any; }
declare module "write-file-atomic" { declare var exports: any; }
